version: '3.8'
services:
  react-frontend:
    container_name: react-frontend-app # Имя контейнера
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Пробрасываем порт 3000
    volumes:
      - .:/app # Подключаем проект как volume для автообновления
      - /app/node_modules # Исключаем node_modules из volume
    environment:
      - CHOKIDAR_USEPOLLING=true # Включаем режим polling для наблюдения за изменениями
